backend/modules/tutor/controllers/DailyTesController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "DailyTesController".
*/
class DailyTesController extends \backend\modules\tutor\controllers\base\DailyTesController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/DefaultController.php
<?php

namespace backend\modules\tutor\controllers;

use yii\web\Controller;

/**
 * Default controller for the `akademik` module
 */
class DefaultController extends Controller
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
}

backend/modules/tutor/controllers/FinalTesController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "FinalTesController".
*/
class FinalTesController extends \backend\modules\tutor\controllers\base\FinalTesController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/JadwalPelajaranController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "JadwalPelajaranController".
*/
class JadwalPelajaranController extends \backend\modules\tutor\controllers\base\JadwalPelajaranController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/JurnalHarianController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "JurnalHarianController".
*/
class JurnalHarianController extends \backend\modules\tutor\controllers\base\JurnalHarianController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/LaporanHarianSiswaController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "LaporanHarianSiswaController".
*/
class LaporanHarianSiswaController extends \backend\modules\tutor\controllers\base\LaporanHarianSiswaController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/MataPelajaranController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "MataPelajaranController".
*/
class MataPelajaranController extends \backend\modules\akademik\controllers\base\MataPelajaranController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/MidTesController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "MidTesController".
*/
class MidTesController extends \backend\modules\tutor\controllers\base\MidTesController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/PretesController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "PretesController".
*/
class PretesController extends \backend\modules\tutor\controllers\base\PretesController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/RaportController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "RaportController".
*/
class RaportController extends \backend\modules\tutor\controllers\base\RaportController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/SilabusController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "SilabusController".
*/
class SilabusController extends \backend\modules\tutor\controllers\base\SilabusController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/SpeakingTesController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "SpeakingTesController".
*/
class SpeakingTesController extends \backend\modules\tutor\controllers\base\SpeakingTesController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/controllers/TesReportController.php
<?php

namespace backend\modules\tutor\controllers;

class TesReportController extends \backend\modules\tutor\controllers\base\TesReportController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }

}

backend/modules/tutor/controllers/UnitTesController.php
<?php

namespace backend\modules\tutor\controllers;

/**
* This is the class for controller "UnitTesController".
*/
class UnitTesController extends \backend\modules\tutor\controllers\base\UnitTesController
{
    public function beforeAction($action)
    {
        $this->layout = 'main'; //your layout name
        return parent::beforeAction($action);
    }
}

backend/modules/tutor/views/daily-tes/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\DailyTes $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="daily-tes-form">

    <?php $form = ActiveForm::begin([
    'id' => 'DailyTes',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error',
    'options'=>['enctype'=>'multipart/form-data'],
    ]
    );
    ?>

    <div class="clearfix"></div>
    <div class="box box-primary">
        <div class="box-header with-border">
                <h3 class="box-title">Form</h3>
        </div>

        <div class="box-body">
			<?= $form->field($model, 'siswa')->widget(\kartik\select2\Select2::className(),[
                'data'=>\yii\helpers\ArrayHelper::map(\app\models\Siswa::find()->all(),'id','nama_lengkap'),
                'options'=>[
                        'prompt'=>'Pilih Siswa'
                ]
            ]) ?>
            <?= $form->field($model, 'pelajaran')->widget(\kartik\select2\Select2::className(),[
                'data'=>\yii\helpers\ArrayHelper::map(\app\models\MataPelajaran::find()->all(),'id','mata_pelajaran'),
                'options'=>[
                    'prompt'=>'Pilih Pelajaran'
                ]
            ]) ?>
			<?= $form->field($model, 'nilai_1')->textInput() ?>
			<?= $form->field($model, 'nilai_2')->textInput() ?>
			<?= $form->field($model, 'nilai_3')->textInput() ?>
			<?= $form->field($model, 'nilai_4')->textInput() ?>
			<?= $form->field($model, 'nilai_5')->textInput() ?>
			<?= $form->field($model, 'nilai_6')->textInput() ?>
			<?= $form->field($model, 'nilai_7')->textInput() ?>
			<?= $form->field($model, 'nilai_8')->textInput() ?>
        </div>

        <div class="box-footer">
            <?php echo $form->errorSummary($model); ?>

            <?= Html::submitButton(
            '<span class="fa fa-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
            'id' => 'save-' . $model->formName(),
            'class' => 'btn btn-success'
            ]
            );
            ?>
        </div>

    </div>
    <?php ActiveForm::end(); ?>

</div>

backend/modules/tutor/views/daily-tes/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
* @var yii\web\View $this
* @var app\models\DailySearch $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="daily-tes-search">

    <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
    ]); ?>

    		<?= $form->field($model, 'id') ?>

		<?= $form->field($model, 'siswa') ?>

		<?= $form->field($model, 'pelajaran') ?>

		<?= $form->field($model, 'nilai_1') ?>

		<?= $form->field($model, 'nilai_2') ?>

		<?php // echo $form->field($model, 'nilai_3') ?>

		<?php // echo $form->field($model, 'nilai_4') ?>

		<?php // echo $form->field($model, 'nilai_5') ?>

		<?php // echo $form->field($model, 'nilai_6') ?>

		<?php // echo $form->field($model, 'nilai_7') ?>

		<?php // echo $form->field($model, 'nilai_8') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/tutor/views/daily-tes/create.php
<?php

use yii\helpers\Html;

/**
* @var yii\web\View $this
* @var app\models\DailyTes $model
*/

$this->title = 'Create';
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'DailyTes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="giiant-crud daily-tes-create">

    <?= $this->render('_form', [
    'model' => $model,
    ]); ?>

</div>

backend/modules/tutor/views/daily-tes/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\DailySearch $searchModel
 */

$this->title = 'DailyTes';
$this->params['breadcrumbs'][] = $this->title;

if (isset($actionColumnTemplates)) {
    $actionColumnTemplate = implode(' ', $actionColumnTemplates);
    $actionColumnTemplateString = $actionColumnTemplate;
} else {
    Yii::$app->view->params['pageButtons'] = Html::a('<span
    class="fa fa-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']);
    $actionColumnTemplateString = "{view} {update} {delete}";
}

?>
<div class="giiant-crud daily-tes-index">

    <?php //             echo $this->render('_search', ['model' =>$searchModel]);
    ?>


    <?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

    <div class="pull-left">
        <?= Html::a('<span class="fa fa-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
    </div>

    <div class="pull-right">


        <?=
        \yii\bootstrap\ButtonDropdown::widget(
            [
                'id' => 'giiant-relations',
                'encodeLabel' => false,
                'label' => '<span class="fa fa-paperclip"></span> ' . 'Relations',
                'dropdown' => [
                    'options' => [
                        'class' => 'dropdown-menu-right'
                    ],
                    'encodeLabels' => false,
                    'items' => []
                ],
                'options' => [
                    'class' => 'btn-default'
                ]
            ]
        );
        ?>    </div>
</div><br clear="all"><br>

<div class="clearfix"></div>

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Data <?= Yii::t('app', 'DailyTes') ?></h3>
    </div>

    <div class="box-body">
        <div class="table-responsive">
            <?= GridView::widget([
                'layout' => '{summary}{pager}{items}{pager}',
                'dataProvider' => $dataProvider,
                'pager' => [
                    'class' => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => 'First',
                    'lastPageLabel' => 'Last'],
                'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                'headerRowOptions' => ['class' => 'x'],
                'columns' => [

                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => $actionColumnTemplateString,
                        'urlCreator' => function ($action, $model, $key, $index) {
                            // using the column name as key, not mapping to 'id' like the standard generator
                            $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string)$key];
                            $params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
                            return Url::toRoute($params);
                        },
                        'contentOptions' => ['nowrap' => 'nowrap']
                    ],
                    [
                        'attribute' => 'siswa',
                        'value' => function ($data) {
                            return \app\models\Siswa::find($data->siswa)->one()->nama_lengkap;
                        }
                    ],
                    [
                        'attribute' => 'pelajaran',
                        'value' => function ($data) {
                            return \app\models\MataPelajaran::find($data->pelajaran)->one()->mata_pelajaran;
                        }
                    ],
                    'nilai_1',
                    'nilai_2',
                    'nilai_3',
                    'nilai_4',
                    'nilai_5',
                    'nilai_6',
                    'nilai_7',
                    'nilai_8',
                ],
            ]); ?>
        </div>
    </div>
</div>


<?php \yii\widgets\Pjax::end() ?>

backend/modules/tutor/views/daily-tes/update.php
<?php

use yii\helpers\Html;

/**
* @var yii\web\View $this
* @var app\models\DailyTes $model
*/

$this->title = Yii::t('app', 'DailyTes') . $model->id . ', ' . 'Edit';
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'DailyTes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Edit';
?>
<div class="giiant-crud daily-tes-update">

    <div class="crud-navigation">
        <?= Html::a('<span class="fa fa-eye-open"></span> ' . 'View', ['view', 'id' => $model->id], ['class' => 'btn btn-default']) ?>
    </div>

    <br clear="all" />

    <?php echo $this->render('_form', [
    'model' => $model,
    ]); ?>

</div>

backend/modules/tutor/views/daily-tes/view.php
<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\DailyTes $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'DailyTes');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'DailyTes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud daily-tes-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>
    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="fa fa-pencil"></span> ' . 'Edit',
            [ 'update', 'id' => $model->id],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="fa fa-plus"></span> ' . 'New',
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="fa fa-list"></span> '
            . 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div><br  clear="all">

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Detail </h3>
        </div>

        <div class="box-body">
            <?php $this->beginBlock('app\models\DailyTes'); ?>

            
            <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                    'id',
                [
                    'attribute'=>'siswa',
                    'value'=>\app\models\Siswa::find($model->siswa)->one()->nama_lengkap
                ],
                [
                    'attribute'=>'pelajaran',
                    'value'=>\app\models\MataPelajaran::find($model->pelajaran)->one()->mata_pelajaran
                ],
        'nilai_1',
        'nilai_2',
        'nilai_3',
        'nilai_4',
        'nilai_5',
        'nilai_6',
        'nilai_7',
        'nilai_8',
            ],
            ]); ?>

            
            <hr/>

            <?= Html::a('<span class="fa fa-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
            [
            'class' => 'btn btn-danger',
            'data-confirm' => '' . 'Are you sure to delete this item?' . '',
            'data-method' => 'post',
            ]); ?>
            <?php $this->endBlock(); ?>


            
            <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['app\models\DailyTes'],
    'active'  => true,
], ]
                 ]
    );
    ?>        </div>

    </div>


</div>

backend/modules/tutor/views/mata-pelajaran/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\MataPelajaran $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="mata-pelajaran-form">

    <?php $form = ActiveForm::begin([
    'id' => 'MataPelajaran',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error',
    'options'=>['enctype'=>'multipart/form-data'],
    ]
    );
    ?>

    <div class="clearfix"></div>
    <div class="box box-primary">
        <div class="box-header with-border">
                <h3 class="box-title">Form</h3>
        </div>

        <div class="box-body">
			<?= $form->field($model, 'mata_pelajaran')->textInput(['maxlength' => true]) ?>
        </div>

        <div class="box-footer">
            <?php echo $form->errorSummary($model); ?>

            <?= Html::submitButton(
            '<span class="fa fa-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
            'id' => 'save-' . $model->formName(),
            'class' => 'btn btn-success'
            ]
            );
            ?>
        </div>

    </div>
    <?php ActiveForm::end(); ?>

</div>

backend/modules/tutor/views/mata-pelajaran/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
* @var yii\web\View $this
* @var app\models\MataPelajaranSearch $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="mata-pelajaran-search">

    <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
    ]); ?>

    		<?= $form->field($model, 'id') ?>

		<?= $form->field($model, 'mata_pelajaran') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/tutor/views/mata-pelajaran/create.php
<?php

use yii\helpers\Html;

/**
* @var yii\web\View $this
* @var app\models\MataPelajaran $model
*/

$this->title = 'Create';
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'MataPelajarans'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="giiant-crud mata-pelajaran-create">

    <?= $this->render('_form', [
    'model' => $model,
    ]); ?>

</div>

backend/modules/tutor/views/mata-pelajaran/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
    * @var app\models\MataPelajaranSearch $searchModel
*/

$this->title = 'MataPelajarans';
$this->params['breadcrumbs'][] = $this->title;

if (isset($actionColumnTemplates)) {
$actionColumnTemplate = implode(' ', $actionColumnTemplates);
$actionColumnTemplateString = $actionColumnTemplate;
} else {
Yii::$app->view->params['pageButtons'] = Html::a('<span
    class="fa fa-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']);
$actionColumnTemplateString = "{view} {update} {delete}";
}

?>
<div class="giiant-crud mata-pelajaran-index">

    <?php //             echo $this->render('_search', ['model' =>$searchModel]);
        ?>

    
    <?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

            <div class="pull-left">
            <?= Html::a('<span class="fa fa-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
        </div>
        
    <div class="pull-right">

                                                        
        <?= 
        \yii\bootstrap\ButtonDropdown::widget(
        [
        'id' => 'giiant-relations',
        'encodeLabel' => false,
        'label' => '<span class="fa fa-paperclip"></span> ' . 'Relations',
        'dropdown' => [
        'options' => [
        'class' => 'dropdown-menu-right'
        ],
        'encodeLabels' => false,
        'items' => [            [
                'url' => ['jadwal-pelajaran/index'],
                'label' => '<i class="fa fa-arrow-right">&nbsp;' . 'Jadwal Pelajaran' . '</i>',
            ],            [
                'url' => ['silabus/index'],
                'label' => '<i class="fa fa-arrow-right">&nbsp;' . 'Silabus' . '</i>',
            ],]
        ],
        'options' => [
        'class' => 'btn-default'
        ]
        ]
        );
        ?>    </div>
</div><br clear="all"><br>

    <div class="clearfix"></div>

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Data <?= Yii::t('app', 'MataPelajarans') ?></h3>
        </div>

        <div class="box-body">
            <div class="table-responsive">
                <?= GridView::widget([
                'layout' => '{summary}{pager}{items}{pager}',
                'dataProvider' => $dataProvider,
                'pager' => [
                'class' => yii\widgets\LinkPager::className(),
                'firstPageLabel' => 'First',
                'lastPageLabel' => 'Last'                ],
                                    'filterModel' => $searchModel,
                                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                'headerRowOptions' => ['class'=>'x'],
                'columns' => [

                        [
            'class' => 'yii\grid\ActionColumn',
            'template' => $actionColumnTemplateString,
            'urlCreator' => function($action, $model, $key, $index) {
                // using the column name as key, not mapping to 'id' like the standard generator
                $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                $params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
                return Url::toRoute($params);
            },
            'contentOptions' => ['nowrap'=>'nowrap']
        ],
			'mata_pelajaran',
                ],
                ]); ?>
            </div>
        </div>
    </div>


<?php \yii\widgets\Pjax::end() ?>

backend/modules/tutor/views/mata-pelajaran/update.php
<?php

use yii\helpers\Html;

/**
* @var yii\web\View $this
* @var app\models\MataPelajaran $model
*/

$this->title = Yii::t('app', 'MataPelajaran') . $model->id . ', ' . 'Edit';
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'MataPelajarans'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Edit';
?>
<div class="giiant-crud mata-pelajaran-update">

    <div class="crud-navigation">
        <?= Html::a('<span class="fa fa-eye-open"></span> ' . 'View', ['view', 'id' => $model->id], ['class' => 'btn btn-default']) ?>
    </div>

    <br clear="all" />

    <?php echo $this->render('_form', [
    'model' => $model,
    ]); ?>

</div>

backend/modules/tutor/views/mid-tes/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\MidTes $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="mid-tes-form">

    <?php $form = ActiveForm::begin([
    'id' => 'MidTes',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error',
    'options'=>['enctype'=>'multipart/form-data'],
    ]
    );
    ?>

    <div class="clearfix"></div>
    <div class="box box-primary">
        <div class="box-header with-border">
                <h3 class="box-title">Form</h3>
        </div>

        <div class="box-body">
            <?= $form->field($model, 'siswa')->widget(\kartik\select2\Select2::className(),[
                'data'=>\yii\helpers\ArrayHelper::map(\app\models\Siswa::find()->all(),'id','nama_lengkap'),
                'options'=>[
                    'prompt'=>'Pilih Siswa'
                ]
            ]) ?>
            <?= $form->field($model, 'pelajaran')->widget(\kartik\select2\Select2::className(),[
                'data'=>\yii\helpers\ArrayHelper::map(\app\models\MataPelajaran::find()->all(),'id','mata_pelajaran'),
                'options'=>[
                    'prompt'=>'Pilih Pelajaran'
                ]
            ]) ?>
			<?= $form->field($model, 'nilai')->textInput() ?>
        </div>

        <div class="box-footer">
            <?php echo $form->errorSummary($model); ?>

            <?= Html::submitButton(
            '<span class="fa fa-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
            'id' => 'save-' . $model->formName(),
            'class' => 'btn btn-success'
            ]
            );
            ?>
        </div>

    </div>
    <?php ActiveForm::end(); ?>

</div>